"use client"

import { useState, useEffect } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { DashboardLayout } from "@/components/dashboard-layout"
import { ArrowLeft, Download, FileText, Calendar, TrendingUp } from "lucide-react"
import toast, { Toaster } from 'react-hot-toast'

interface ReportData {
  symbol: string
  analysis: string
  timestamp: string
  data: any
}

export default function AnalysisReportPage() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const reportId = searchParams.get('id')

  const [reportData, setReportData] = useState<ReportData | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    if (reportId) {
      const storedData = localStorage.getItem(reportId)
      if (storedData) {
        try {
          const data = JSON.parse(storedData) as ReportData
          setReportData(data)
        } catch (error) {
          console.error('Error parsing report data:', error)
          toast.error('Failed to load report data')
        }
      } else {
        toast.error('Report not found')
      }
    }
    setIsLoading(false)
  }, [reportId])

  const handleDownloadReport = () => {
    if (!reportData) return

    const pdfContent = `
STOCK ANALYSIS REPORT
Generated by StockFlow AI Remote Agent
Date: ${new Date(reportData.timestamp).toLocaleDateString()}
Symbol: ${reportData.symbol}

${reportData.analysis}

---
This report was generated by StockFlow's AI analysis system.
Disclaimer: This analysis is for informational purposes only and should not be considered as investment advice.
    `.trim()

    const blob = new Blob([pdfContent], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.style.display = 'none'
    a.href = url
    a.download = `${reportData.symbol}_analysis_report.txt`
    document.body.appendChild(a)
    a.click()
    window.URL.revokeObjectURL(url)
    document.body.removeChild(a)

    toast.success('Report downloaded successfully!')
  }

  const formatAnalysisText = (text: string) => {
    const sections = text.split('\n\n')

    return sections.map((section, sectionIndex) => {
      const lines = section.split('\n')

      // Check if this is a main section header (contains numbers like "1.", "2." etc.)
      if (lines[0] && lines[0].match(/^\d+\.\s*\*\*([^*]+)\*\*/)) {
        const headerMatch = lines[0].match(/^\d+\.\s*\*\*([^*]+)\*\*/)
        const headerText = headerMatch ? headerMatch[1] : lines[0]
        const remainingText = lines.slice(1).join('\n')

        return (
          <div key={sectionIndex} className="mb-8">
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-4 mb-4 border-l-4 border-blue-500">
              <h3 className="text-xl font-bold text-blue-900 flex items-center">
                <span className="bg-blue-500 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm mr-3">
                  {lines[0].match(/^\d+/) ? lines[0].match(/^\d+/)?.[0] : '•'}
                </span>
                {headerText}
              </h3>
            </div>
            <div className="pl-6 space-y-2">
              {formatSectionContent(remainingText)}
            </div>
          </div>
        )
      }

      // Regular content formatting
      return (
        <div key={sectionIndex} className="mb-6 space-y-2">
          {lines.map((line, lineIndex) => {
            if (line.trim() === '') return <div key={lineIndex} className="h-2"></div>

            // Bold headers (**text**)
            if (line.includes('**')) {
              const parts = line.split(/\*\*(.*?)\*\*/)
              return (
                <div key={lineIndex} className="font-semibold text-gray-800 text-lg mb-3 mt-4">
                  {parts.map((part, i) => (
                    i % 2 === 1 ? <strong key={i} className="text-blue-800">{part}</strong> : part
                  ))}
                </div>
              )
            }

            // Bullet points
            if (line.trim().startsWith('•') || line.trim().startsWith('-')) {
              return (
                <div key={lineIndex} className="flex items-start ml-4 mb-2">
                  <span className="text-blue-500 mr-2 mt-1">•</span>
                  <span className="text-gray-700 leading-relaxed">{line.replace(/^[•-]\s*/, '')}</span>
                </div>
              )
            }

            // Regular text
            return (
              <div key={lineIndex} className="text-gray-700 leading-relaxed mb-2">
                {line}
              </div>
            )
          })}
        </div>
      )
    })
  }

  const formatSectionContent = (content: string) => {
    return content.split('\n').map((line, index) => {
      if (line.trim() === '') return <div key={index} className="h-1"></div>

      if (line.trim().startsWith('•') || line.trim().startsWith('-')) {
        return (
          <div key={index} className="flex items-start mb-2">
            <span className="text-blue-500 mr-2 mt-1 text-sm">▪</span>
            <span className="text-gray-700 text-sm leading-relaxed">{line.replace(/^[•-]\s*/, '')}</span>
          </div>
        )
      }

      return (
        <div key={index} className="text-gray-700 text-sm leading-relaxed mb-2">
          {line}
        </div>
      )
    })
  }

  if (isLoading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center min-h-screen">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-black"></div>
        </div>
      </DashboardLayout>
    )
  }

  if (!reportData) {
    return (
      <DashboardLayout>
        <Toaster />
        <div className="p-6">
          <div className="flex items-center justify-center min-h-[400px]">
            <Card className="max-w-md w-full">
              <CardContent className="text-center py-8">
                <FileText className="mx-auto mb-4 text-gray-400 w-12 h-12" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  Report Not Found
                </h3>
                <p className="text-gray-600 mb-4">
                  The requested analysis report could not be found.
                </p>
                <Button onClick={() => router.push('/statistics')}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Statistics
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </DashboardLayout>
    )
  }

  return (
    <DashboardLayout>
      <Toaster />
      <div className="p-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center space-x-4">
            <Button
              variant="outline"
              onClick={() => router.push('/statistics')}
              className="flex items-center"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Statistics
            </Button>
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Analysis Report</h1>
              <div className="flex items-center space-x-4 mt-2 text-sm text-gray-600">
                <div className="flex items-center space-x-1">
                  <TrendingUp className="w-4 h-4" />
                  <span>{reportData.symbol}</span>
                </div>
                <div className="flex items-center space-x-1">
                  <Calendar className="w-4 h-4" />
                  <span>{new Date(reportData.timestamp).toLocaleDateString()}</span>
                </div>
              </div>
            </div>
          </div>
          <Button
            onClick={handleDownloadReport}
            className="bg-green-600 hover:bg-green-700 text-white"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </Button>
        </div>

        {/* Report Content */}
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Report Header Card */}
          <Card className="overflow-hidden">
            <CardHeader className="bg-gradient-to-r from-slate-900 via-blue-900 to-indigo-900 text-white">
              <div className="flex items-center space-x-4">
                <div className="w-16 h-16 bg-white/20 rounded-lg flex items-center justify-center">
                  <img
                    src="https://avatars.githubusercontent.com/u/223376538?s=200&v=4"
                    alt="AI Analysis"
                    className="w-12 h-12 rounded-lg"
                  />
                </div>
                <div className="flex-1">
                  <CardTitle className="text-2xl font-bold mb-2">
                    📊 Stock Analysis Report: {reportData.symbol}
                  </CardTitle>
                  <div className="text-blue-200 text-sm">
                    🤖 Generated by StockFlow AI Remote Agent • {new Date(reportData.timestamp).toLocaleDateString()}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-white/80 text-sm">Analysis Complete</div>
                  <div className="bg-green-500/20 text-green-200 px-3 py-1 rounded-full text-xs mt-1">
                    ✅ Professional Report
                  </div>
                </div>
              </div>
            </CardHeader>
          </Card>

          {/* Executive Summary */}
          <Card>
            <CardHeader className="bg-gradient-to-r from-emerald-50 to-teal-50 border-b">
              <CardTitle className="text-xl text-emerald-800 flex items-center">
                <span className="bg-emerald-500 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm mr-3">
                  📋
                </span>
                Executive Summary
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl p-6 border border-blue-200">
                <div className="text-gray-700 leading-relaxed">
                  <p className="font-semibold text-blue-900 mb-3">
                    🎯 Comprehensive AI-Powered Financial Analysis
                  </p>
                  <p>
                    This detailed analysis leverages advanced AI algorithms to evaluate the financial performance,
                    market positioning, and investment potential of <strong className="text-blue-800">{reportData.symbol}</strong>.
                    Our analysis covers 10 key areas including financial health, valuation metrics, risk assessment,
                    and growth prospects to provide you with actionable investment insights.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Main Analysis Content */}
          <Card>
            <CardHeader className="bg-gradient-to-r from-blue-50 to-indigo-50 border-b">
              <CardTitle className="text-xl text-blue-800 flex items-center">
                <span className="bg-blue-500 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm mr-3">
                  🔍
                </span>
                Detailed Analysis Results
              </CardTitle>
            </CardHeader>
            <CardContent className="p-8">
              <div className="space-y-8">
                {formatAnalysisText(reportData.analysis)}
              </div>
            </CardContent>
          </Card>

          {/* Disclaimer */}
          <Card className="border-amber-200">
            <CardHeader className="bg-gradient-to-r from-amber-50 to-yellow-50 border-b border-amber-200">
              <CardTitle className="text-lg text-amber-800 flex items-center">
                <span className="text-amber-600 mr-3">⚠️</span>
                Investment Disclaimer & Risk Warning
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 bg-amber-50/30">
              <div className="space-y-4 text-amber-800">
                <div className="flex items-start space-x-3">
                  <span className="text-amber-600 mt-1">🚨</span>
                  <p className="text-sm leading-relaxed">
                    <strong>AI-Generated Analysis:</strong> This report is generated by artificial intelligence
                    and is provided for informational purposes only. It should not be considered as personalized
                    investment advice or a recommendation to buy, sell, or hold any security.
                  </p>
                </div>
                <div className="flex items-start space-x-3">
                  <span className="text-amber-600 mt-1">📊</span>
                  <p className="text-sm leading-relaxed">
                    <strong>Professional Consultation Required:</strong> Always conduct your own research and
                    consult with qualified financial advisors before making any investment decisions. Past
                    performance does not guarantee future results.
                  </p>
                </div>
                <div className="flex items-start space-x-3">
                  <span className="text-amber-600 mt-1">💰</span>
                  <p className="text-sm leading-relaxed">
                    <strong>Risk Acknowledgment:</strong> All investments carry risk of loss. You should only
                    invest money you can afford to lose and ensure any investment aligns with your risk
                    tolerance and financial objectives.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Footer */}
          <div className="text-center py-8 border-t border-gray-200">
            <div className="space-y-2">
              <div className="text-lg font-semibold text-gray-700">
                🚀 StockFlow AI Analysis Engine
              </div>
              <div className="text-sm text-gray-500">
                Report generated on {new Date(reportData.timestamp).toLocaleString()}
              </div>
              <div className="text-xs text-gray-400">
                Powered by Advanced AI Financial Analysis Technology
              </div>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  )
}